### ISSUE TITLE
Support library version should be set to latest

### ISSUE THREAD

**Issue by dimsuz** [zagum/Android-ExpandIcon#2]
Hmm, I see a commit with message "downgrade support library to 25.0.1".

I wonder if this breaks the view somehow and if yes, author should be aware, that if this library is used in some other project, gradle will by default pick the project's support lib version (unless different resolution strategy is selected), so it could potentially end up with higher version still (...and break?)

**Comment by zagum** [comment]
removed support library dependency in version 1.1.0
