### ISSUE TITLE
(startPosition.y - center.y) * Math.cos(angle))==0

### ISSUE THREAD

**Issue by daiwenbo88** [zagum/Android-ExpandIcon#7]
This animation based on the Path to write is very good, it makes me learned a lot Thank you for your open source
Look at the code：
private void rotate(@NonNull Point startPosition, double degrees, @NonNull Point target) {
    double angle = Math.toRadians(degrees);
    int x = (int) (center.x + (startPosition.x - center.x) * Math.cos(angle) -
        (startPosition.y - center.y) * Math.sin(angle));
    int y = (int) (center.y + (startPosition.x - center.x) * Math.sin(angle) +
        (startPosition.y - center.y) * Math.cos(angle));
    target.set(x, y);
  }
-----------------------------------------》
private void calculateArrowMetrics(int width, int height) {
    final int arrowMaxWidth = (height >= width ? width : height);
    if (useDefaultPadding) {
      padding = (int) (PADDING_PROPORTION * arrowMaxWidth);
    }
    final int arrowWidth = arrowMaxWidth - 2 * padding;
    float thickness = (int) (arrowWidth * THICKNESS_PROPORTION);
    paint.setStrokeWidth(thickness);

    center.set(width / 2, height / 2);
    left.set(center.x - arrowWidth / 2, center.y);
    right.set(center.x + arrowWidth / 2, center.y);
  }
---------------------------------------》
      rotate(left, -alpha, tempLeft);
      rotate(right, alpha, tempRight);
----------------------------------------》
I feel：
     left.set(center.x - arrowWidth / 2, center.y);
    right.set(center.x + arrowWidth / 2, center.y);
so:
    (startPosition.y - center.y) * Math.sin(angle));  In the：  startPosition.y==center.y ?

**Comment by zagum** [comment]
Yes, you are right :) 
I did't replace it with zero, because it's a well known formula to rotate the coordinates; 
The start state of arrow is line (with zero angle between lines, so y = getHeight / 2 = center.y)

**Comment by zagum** [comment]
Can i close your issue ?))
