### ISSUE TITLE
Color for intermediate state and setAnimationSpeed() method

### ISSUE THREAD

**Issue by alexandru-pinzaru** [zagum/Android-ExpandIcon#8]
Would be nice to be able to set the color for state intermediate, for cases where for example we use the arrow only between fraction 0.5 to 1.0.

Also a way to set the animation speed programmatically would be useful.

Thanks!

**Comment by zagum** [comment]
Ok, i'll try to do it as soon as i can :)

**Comment by zagum** [comment]
done in v. 1.2.0
